{"name": "test_login_failed[case1]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('url', <SubRequest 'init' for <Function test_login_failed[case1]>>)", "trace": "file D:\\Test_framework\\Web_auto\\TestCases\\test_login.py, line 11\n      @pytest.mark.parametrize(\"case\", td.invalid_data)\n      def test_login_failed(self, case, back_login):\nfile D:\\Test_framework\\Web_auto\\TestCases\\conftest.py, line 38\n  @pytest.fixture(scope=\"class\")\n  def back_login(init):\nfile D:\\Test_framework\\Web_auto\\TestCases\\conftest.py, line 28\n  @pytest.fixture(scope=\"class\")\n  def init(url):\nE       fixture 'url' not found\n>       available fixtures: back_login, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, init, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\Test_framework\\Web_auto\\TestCases\\conftest.py:28"}, "parameters": [{"name": "case", "value": "{'user': '18684720553', 'passwd': '', 'check': '请输入登录密码！'}"}], "start": 1647847718711, "stop": 1647847718711, "uuid": "1298e256-b6be-4d42-a343-be7751968f05", "historyId": "ea5995e15b9d4b136df14d26279df77d", "testCaseId": "76d8a45a420a86cfad6f84d07a44a7e3", "fullName": "TestCases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_login')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}