{"name": "test_login_failed[case0]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('init', <SubRequest 'back_login' for <Function test_login_failed[case0]>>)", "trace": "file D:\\Test_framework\\Web_auto\\TestCases\\test_login1.py, line 11\n      @pytest.mark.parametrize(\"case\", td.invalid_data)\n      def test_login_failed(self, case, back_login):\nfile D:\\Test_framework\\Web_auto\\TestCases\\conftest.py, line 38\n  @pytest.fixture(scope=\"class\")\n  def back_login(init):\nE       fixture 'init' not found\n>       available fixtures: back_login, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, login, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\Test_framework\\Web_auto\\TestCases\\conftest.py:38"}, "parameters": [{"name": "case", "value": "{'user': '', 'passwd': '', 'check': '请输入账号/邮箱/手机号！'}"}], "start": 1647849780702, "stop": 1647849780702, "uuid": "b799796d-68c4-4220-a58a-f77617f3e2bd", "historyId": "6c71b318337ddf052fb90e11baa07cd4", "testCaseId": "6d230ca66b6dfc3f741b1dec342650f6", "fullName": "TestCases.test_login1.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_login')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login1"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "19376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login1"}]}